### ISSUE TITLE
Добавить параметр Nescafe

### ISSUE THREAD

**Issue by inexcode** [inexcode/ixizi#1]
Цитирую @RareScrap
> Я, Юрий Андреевич, желаю в видеть в программном обеспеченье тов-ща inex'а (далее продукт) функционал, который позволит мне наслаждаться вкусом любимого кофе "нескафе" из нулевых (далее кофе). Желаю 15% шанс плевка в стакан и возможность заваривать холодной водой

- [x] Реализовать рандомный выбор продуктов Нескафе
- [x] 1d5 для температуры воды
- [x] 1d4 для степени растворённости 
- [x] При фатальной неудаче (1d10 меньше трёх), плевок в стакан.

**Comment by RareScrap** [comment]
YEEEEEES!
